server:
  port: 6060
spring:
  redis:
    host: 47.109.93.154
    port: 6379
    password: Hins
    database: 0
    lettuce:
      pool:
        max-active: 32
        max-idle: 16
        min-idle: 8
  devtools:
    restart:
      enabled: true
